# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 13:57
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import User


def create_levels_for_users(apps, schema_editor):
    Level = apps.get_model('task_manager', 'Level')
    for user in User.objects.all():
        Level.objects.create(user_id=user.id, experience=0)


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_levels_for_users),
    ]
